### ISSUE TITLE
windows可以训练吗！

### ISSUE THREAD

**Issue by Cjh2312** [xueleichen/PyTorch-Underwater-Image-Enhancement#1]
感谢您的代码，我想问一下在windows上可以训练吗！谢谢

**Comment by xueleichen** [comment]
Hi, I think the code can run on windows if you install anaconda and pytorch. 

However, the file system in windows use \ while that in ubuntu use /. So you need to replace / in this repository with \

**Comment by Cjh2312** [comment]
**thank you very much!**
