### ISSUE TITLE
why the batch size is 1

### ISSUE THREAD

**Issue by fengxiaohu** [xueleichen/PyTorch-Underwater-Image-Enhancement#4]
Usually I set the batch size 64 or 128 during the training process.
I assume that the parameter is depend on your GPU memory,So can I set it to 64 when I own 3080ti to accelerate the training

**Comment by xueleichen** [comment]
Hi @fengxiaohu , I think it is a convention that people use small batch sizes in low-level computer vision tasks (like enhancement or superresolution). I just followed this rule.

Some examples are:
https://github.com/Li-Chongyi/Water-Net_Code
https://github.com/yulunzhang/RCAN
https://github.com/xahidbuffon/SRDRM
These three github repos use the batch size of 1 or 2.

But you can try large batch sizes and see what the results look like.

**Comment by fengxiaohu** [comment]
thanks for reply,I will try to increase the batch_size  and see what will happen
